### ISSUE TITLE
HSM/pkcs11 support 

### ISSUE THREAD

**Issue by gillespilloudkerlink** [jawah/niquests#102]
With growing need of security from the application, the support of secured-stored certificate becomes essential.

It would be great to have the support of PKCS#11 ssl engine with the capacity to read the certificate at the pkcs11 format
`client_key = 'pkcs11:token=testtoken;object=mykey;pin-value=12341234'`

Opened questions regarding this need in www : 
https://stackoverflow.com/questions/57976489/hsm-integration-with-python-requests-module
pycurl support this feature.

**Comment by Ousret** [comment]
I understand the usefulness of having a shortcut to PKCS11-type certificates.
Right away, I don't think I can add HSM access in Niquests due to my actual maintenance burden for now.

In the meantime, you could directly use a dedicated library capable of providing the cert and key from that device and once you have them, put them into `cert=(pub, priv)` keyword argument.

For a side note, it is planned to support loading p12 file automatically soon.

Regards,
