### ISSUE TITLE
[question] Use niquests with requests-oauth HOWTO

### ISSUE THREAD

**Issue by gclements-chwy** [jawah/niquests#96]
Hi just a question.

I see a few mentions of `requests-oauthlib` in the documentation but how do we get `requests-oauthlib` to use niquests instead of requests?

**Comment by Ousret** [comment]
Of course, you may try this at first https://niquests.readthedocs.io/en/latest/dev/migrate.html#maintainer-migration and report back.
I will try to find a more suitable way to make it work. will be back asap.

**Comment by gclements-chwy** [comment]
Oooo, I think that would work, but don't feel comfortable with that.

Probably the right thing to do is to fork `requests-oauth` and update it to use niquests then release it to pypi as `niquests-oauth` making sure that you can pull updates from `requests-oauth` upstream so any fixes to `requests-oauth` end up in `niquests-oauth`.

**Comment by Ousret** [comment]
> Oooo, I think that would work, but don't feel comfortable with that.

I understand, I pointed to it as a very temporary and local solution.

> Probably the right thing to do is to fork requests-oauth and update it to use niquests then release it to pypi as niquests-oauth

that would be the best case scenario.

**Comment by Ousret** [comment]
Meanwhile, you may find a better suitable example bellow.

```python
import niquests
from oauthlib.oauth2 import BackendApplicationClient
import requests_oauthlib

requests_oauthlib.OAuth2Session.__bases__ = (niquests.Session,)

client_id = "xxxxxxxxxxxxxxxxxxxxxxxxxxx"
client_secret = "xxxxxxxxxxxxxxxxxxxxxxxxxxx"
token_url = 'https://api.github.com/token'

if __name__ == "__main__":
    client = BackendApplicationClient(client_id=client_id)
    sample = requests_oauthlib.OAuth2Session(client=client)

    token = sample.fetch_token(token_url, client_secret=client_secret)
```

this is a no-op code, just as an example, the key element to be considered is `requests_oauthlib.OAuth2Session.__bases__ = (niquests.Session,)`.

**Comment by kseistrup** [comment]
I hope I'm not side-tracking the thread, but I feel it is related to a question I've wanted to ask:

I have used the `import niquests as requests` method (with fallback to `import requests` upon failure) with success. However, it is time consuming to patch each application individually (and re-patch upon application upgrade), so here's my question:

Since `niquests` claims drop-in compatibility, would it be possible simply to install `niquests` as `requests` and then each and every application would use `niquests` even without knowing about it?

E.g., ArchLinux has an optional `provides` attribute for packages that lets admins/users choose between two or more packages that will fulfill the same functionality (imaginary example: `gawk`, `mawk`, and `nawk` could each have a `provides=("awk")` array to signal that you can install any of these to get `awk`). And Debian has its “alternatives”, that does something similar in a vastly different way.

So on ArchLinux, I could simply install let's say `python-niquests-requests` that should have a `provides=("python-requests")` attribute, and then the package manager will remove the original `python-requests` package and install `python-niquests` in its place, and everyone is happy.

Or is `niquests` not _that_ drop-in compatible?

Cheers.

**Comment by Ousret** [comment]
> I have used the import niquests as requests method (with fallback to import requests upon failure) with success. 

Great to see enthusiasm for this solution.

> However, it is time consuming to patch each application individually

I understand the frustration you are dealing with.

> So on ArchLinux, I could simply install let's say python-niquests-requests that should have a provides=("python-requests") attribute, and then the package manager will remove the original python-requests package and install python-niquests in its place, and everyone is happy.

It is possible, but I would keep both scenarii and let the user decide what they want, knowing fully what they are doing.
Moreover, I am more inclined to upgrade/patch one by one rather that in bulk. Here's why:

While Niquests is a drop-in replacement, there's still some tiny changes this and there that can (1~5% of the time) reveal a breaking change. (for example: relying on a broken behavior that are now patched).

Regards,

**Comment by kseistrup** [comment]
> It is possible, but I would keep both scenarii and let the user decide what they want, knowing fully what they are doing.

Thanks, that makes sense. I understand your viewpoint.

What if (I'm happy to post it as a separate issue, or to drop the idea entirely):

```sh
…/site-packages
└── requests     # “fake” requests
   ├── niquests  # original niquests (could also live outside of this tree)
   └── requests  # original requests
```

Would it be possible to install the original `requests` and `niquests` in a directory named `requests`, and then have an `__init__.py` initialization file that:

+ exposes the original `requests` per default — i.e., if the user hasn't excplicitly asked for `niquests`, or
+ exposes the original `niquests` if, say, the environment variable `$PLEASE_USE_NIQUESTS` (or something more sensible) is set.

In that way it will be easy to offer `niquests` to unpatched applications that uses `requests`, and it will be easy to disable `niquests`, should an application use a `requests` feature that is unimplemented or broken.

I hope I'm not wasting your time, I just feel that `niquests` has such a potential.

**Comment by Ousret** [comment]
> I hope I'm not wasting your time, I just feel that niquests has such a potential.

I understand your motivation, and the resulting questions. No harm in that.

> Would it be possible to install the original requests and niquests in a directory named requests, and then have an __init__.py initialization file that:

Unfortunately, you cannot. People don't just do `import requests`, they tend to import sub modules directly too.
The idea cannot stand without a substantial effort. I wouldn't risk it.

---

Do you @gclements-chwy accept the answer I proposed ? If your question is answered, feel free to close this issue.
I will update the documentation with clarifications and later think about the idea on having forks of popular extensions.

**Comment by kseistrup** [comment]
Thanks, I understand. And thanks for your patience.

**Comment by gclements-chwy** [comment]
Yes, I think we can close this issue. Your suggestion: 

```
requests_oauthlib.OAuth2Session.__bases__ = (niquests.Session,)
```

worked well and I was able to test nyquests effectively. 😄

**Comment by ziddey** [comment]
Just wanted to mention that overriding the base class will result in problems when refreshing the token.

In `OAuth2Session.refresh_token`, there's a call to `self.post` with kwarg `withhold_token`:

https://github.com/requests/requests-oauthlib/blob/f33dac32bd065b835b34e7f0a48025700aae1e31/requests_oauthlib/oauth2_session.py#L476-L485

This is fine with Requests' `post` since it passes all kwargs up to `request`:

https://github.com/psf/requests/blob/70298332899f25826e35e42f8d83425124f755a5/src/requests/sessions.py#L626C10-L637

However, Niquests' `post` has hardcoded args/kwargs:

https://github.com/jawah/niquests/blob/9d0281461cb0ffdced5d60a5591076046c3027ac/src/niquests/sessions.py#L793-L811


This then expectedly produces:

```
Session.post() got an unexpected keyword argument 'withhold_token'
```
